name: Get Secret From GCP
on:
  push:
    branches:
    - feature/pradeep
  workflow_dispatch:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Successful Step
        run: echo "This step is successful"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Authenticate to Google Cloud
        id: auth-gcp0
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # - name: Access Secret Details using GCP CLI
      #   id: gcloud-cli
      #   run: |
      #     echo "::group::Accessing Secret Details"
      #     secret_value=$(gcloud secrets versions access latest --secret=github-action)         
      #     echo "SECRET_DETAILS_CLI=$secret_value" >> $GITHUB_ENV
      #     echo "Secret Value: $secret_value"
      #     echo "::endgroup::"

      - name: Access Secret Details using GitHub Action (get-secretmanager-secrets)
        id: github-action-get-secretmanager
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            MY_JSON_SECRET: projects/exam-preparation-300390/secrets/github-action
          min_mask_length: 0

      - name: Get Secret Details from Environment
        run: |-
          echo "Trex Details from ENV: ${{ env.SECRET_DETAILS }}"
          clientId=$(echo '${{ steps.github-action-get-secretmanager.outputs.MY_JSON_SECRET }}' | jq -r '.clientId')
          echo "Client Id : $clientId"

          clientSecret=$(echo '${{ steps.github-action-get-secretmanager.outputs.MY_JSON_SECRET }}' | jq -r '.clientSecret')
          echo "Client Secret: $clientSecret"
