name: Trigger Other Workflow
on:
  push:
    branches:
    - feature/pradeep
  workflow_dispatch:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Successful Step
        run: echo "This step is successful"

      - name: Authenticate to Google Cloud
        id: auth-gcp0
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # - id: 'auth'
      #   name: 'Authenticate to Google Cloud'
      #   uses: 'google-github-actions/auth@v1'
      #   with:
      #     workload_identity_provider: 'projects/132917503746/locations/global/workloadIdentityPools/githubaction/providers/github'
      #     service_account: 'github-actions@exam-preparation-300390.iam.gserviceaccount.com'
      - id: gcloud-cli
        name: Access Secret Details using GCP CLI
        run: |
          gcloud secrets versions access latest --secret=github-action

      - id: github-action-get-secretmanager
        name: Access Secret Details using GitHub Action (get-secretmanager-secrets)
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
          token: exam-preparation-300390/github-action

      - name: Print Secret Value
        run: |-
          echo '${{ steps.secrets.outputs.token }}'
