name: Get Secret From GCP
on:
  push:
    branches:
    - feature/pradeep
  workflow_dispatch:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Successful Step
        run: echo "This step is successful"

      - name: Authenticate to Google Cloud
        id: auth-gcp0
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Access Secret Details using GCP CLI
        id: gcloud-cli
        run: |
          echo "::group::Accessing Secret Details"
          secret_value=$(gcloud secrets versions access latest --secret=github-action)
          echo "Secret Value: $secret_value"
          echo "::endgroup::"

      - name: Access Secret Details using GitHub Action (get-secretmanager-secrets)
        id: github-action-get-secretmanager
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            output1: projects/exam-preparation-300390/secrets/github-action
      - name: Print Secret Value
        run: |-
          echo "Secret Value: ${{ steps.github-action-get-secretmanager.outputs.output1 }}"
