name: Get Secret From GCP
on:
  push:
    branches:
    - feature/pradeep
  workflow_dispatch:

jobs:
  get-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Successful Step
        run: echo "This step is successful"

      - name: Install jq
        run: sudo apt-get install jq

      - name: Authenticate to Google Cloud
        id: auth-gcp0
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Access Secret Details using GCP CLI
        id: gcloud-cli
        run: |
          echo "::group::Accessing Secret Details"
          secret_value=$(gcloud secrets versions access latest --secret=github-action)         
          echo "SECRET_DETAILS_CLI=$secret_value" >> $GITHUB_ENV
          echo "Secret Value: $secret_value"
          echo "::endgroup::"

      - name: Get Secret Details from Environment
        run: |-
          echo "Trex Details from ENV: ${{ env.SECRET_DETAILS_CLI }}"
          Parse JSON to extract specific values
          VALUE=$(echo '$(gcloud secrets versions access latest --secret=github-action)' | jq -r '.clientSecret')
          echo "Extracted Value: $VALUE"



      - name: Access Secret Details using GitHub Action (get-secretmanager-secrets)
        id: github-action-get-secretmanager
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
          secrets: |-
            output1: projects/exam-preparation-300390/secrets/github-action
      - name: Print Secret Value
        run: |-
          echo "Secret Value: ${{ steps.github-action-get-secretmanager.outputs.output1 }}"

      - name: Get Secret Details from Environment
        env:
          SECRET_DETAILS: ${{ steps.github-action-get-secretmanager.outputs.trex-cred-details }}
        run: |-
          echo "Trex Details from ENV: ${{ env.SECRET_DETAILS }}"
          Parse JSON to extract specific values
          VALUE=$(echo '${{ env.SECRET_DETAILS }}' | jq -r '.clientSecret')
          echo "Extracted Value: $VALUE"
