name: Target Workflow
on:
  workflow_dispatch:
  # repository_dispatch:
  #   types: [trigger-other-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Git Command
        run: |
          git config --global init.defaultBranch feature/pradeep
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: print trigger values of source workflow
        run: |
          echo ${{ github.event.client_payload.github.action }}
          echo ${{ github.event.client_payload.github.actor }}
          echo '{"github": ${{ toJson(github) }}}'

      - name: Successful Step
        run: echo "This step is successful"
      # - name: Failing Step
      #   run: exit 1  # Deliberately fail this step
      - name: Another Successful Step
        run: |
          echo "This step is also successful"  
          sleep 100s 
