name: Target Workflow
on:
  workflow_dispatch:
  # repository_dispatch:
  #   types: [trigger-other-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Git Command
        run: |
          git config --global init.defaultBranch feature/pradeep
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: print trigger values of source workflow
        run: |
          echo ${{ github.event.client_payload.github.action }}
          echo ${{ github.event.client_payload.github.actor }}
          echo '{"github": ${{ toJson(github) }}}'

      - name: Successful Step 1 
        run: echo "This step is successful1"
      - name: Another Successful Step 2 with wait time 100s
        run: |
          echo "This step is also successful2"  
          sleep 100s 
      - name: Failing Step 1
        run: |
          exit 1  # Deliberately fail this step
      - name: Successful Step 3  
        run: echo "This step is successful3"

